const initialDishes=[
 {id:'pork',name:'青椒肉丝',image:'assets/icon1.png',ingredients:[['青椒','2个'],['猪肉','300克'],['蒜','2瓣']],steps:['青椒切丝，猪肉切丝后加入少许盐和淀粉抓匀。','热锅放油，将肉丝快速滑炒至变色后盛出。','蒜末爆香，加入青椒翻炒至断生。','倒回肉丝，加生抽和盐调味，翻炒均匀出锅。']},
 {id:'ribs',name:'糖醋排骨',image:'assets/icon8.png',ingredients:[['排骨','500克'],['冰糖','30克'],['醋','2勺']],steps:['排骨冷水下锅焯去血沫。','锅中少油炒化冰糖，放入排骨上色。','加入生抽、醋和热水，小火焖煮。','大火收汁，让糖醋汁均匀裹住排骨。']},
 {id:'egg',name:'西红柿炒鸡蛋',image:'assets/app.png',ingredients:[['鸡蛋','3个'],['西红柿','2个'],['葱','1根']],steps:['西红柿切块，鸡蛋加盐打散。','热锅倒油，将鸡蛋炒成大块后盛出。','炒香葱花，加入西红柿炒出汤汁。','倒回鸡蛋，加少许盐和糖翻匀。']},
 {id:'broccoli',name:'水煮西兰花',image:'assets/icon3.png',ingredients:[['西兰花','1颗'],['蒜','2瓣'],['盐','少许']],steps:['西兰花切小朵，用盐水浸泡后洗净。','水烧开后加少许盐和油。','放入西兰花煮两分钟。','捞出沥水，撒蒜末或蘸酱食用。']}
];
const store={get(k,f){try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}},set(k,v){localStorage.setItem(k,JSON.stringify(v))}};
let dishes=store.get('cook:dishes',initialDishes), cart=store.get('cook:cart',[]), menu=store.get('cook:menu',[]), checked=store.get('cook:checked',[]), page=location.hash.slice(1)||'home',homeTimer,applyingRemote=false;
const app=document.querySelector('#app'), modalRoot=document.querySelector('#modal-root');
const escapeHtml=s=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function cloudPayload(){return{dishes,menu,checked}}
function save(){store.set('cook:dishes',dishes);store.set('cook:cart',cart);store.set('cook:menu',menu);store.set('cook:checked',checked);if(!applyingRemote&&window.CookCloud?.session)CookCloud.scheduleSave(cloudPayload,()=>toast('云端同步暂时失败'))}
function applyCloudPayload(payload){if(!payload||!Array.isArray(payload.dishes))return;applyingRemote=true;dishes=payload.dishes;menu=Array.isArray(payload.menu)?payload.menu:[];checked=Array.isArray(payload.checked)?payload.checked:[];save();applyingRemote=false;render()}
function showLogin(message=''){modalRoot.innerHTML=`<div class="auth-screen"><section class="auth-card"><img src="assets/app.png" alt="朝夕食事"><h1>登录朝夕食事</h1><p>两个人共享同一份菜单与采购清单</p>${message?`<div class="auth-error">${escapeHtml(message)}</div>`:''}<form class="form" id="login-form"><input name="email" type="email" autocomplete="email" required placeholder="邮箱"><input name="password" type="password" autocomplete="current-password" required placeholder="密码"><button class="primary">登录</button></form></section></div>`;document.querySelector('#login-form').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget,button=form.querySelector('button'),data=new FormData(form);button.disabled=true;button.textContent='正在登录…';try{await CookCloud.login(data.get('email').trim(),data.get('password'));modalRoot.innerHTML='';await connectCloud()}catch(error){showLogin(error.message||'登录失败')}}}
async function connectCloud(){try{const row=await CookCloud.load();if(row?.payload&&Array.isArray(row.payload.dishes)){applyCloudPayload(row.payload)}else{await CookCloud.save(cloudPayload())}CookCloud.startPolling(applyCloudPayload,()=>{});toast('云端同步已连接')}catch(error){if(/JWT|登录|token|unauthorized/i.test(error.message||'')){CookCloud.logout();showLogin('登录已过期，请重新登录')}else toast('云端连接失败，本地模式仍可使用')}}
function imageFileToDataUrl(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onerror=reject;reader.onload=()=>{const img=new Image();img.onerror=reject;img.onload=()=>{const max=1000,scale=Math.min(1,max/Math.max(img.width,img.height)),canvas=document.createElement('canvas');canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);resolve(canvas.toDataURL('image/jpeg',.84))};img.src=reader.result};reader.readAsDataURL(file)})}
function toast(msg){const n=document.createElement('div');n.className='toast';n.textContent=msg;document.body.append(n);setTimeout(()=>n.remove(),1800)}
function nav(){document.querySelectorAll('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===page))}
function render(){clearInterval(homeTimer);nav(); if(page==='home')home();if(page==='order')order();if(page==='shop')shop();if(page==='recipe')recipe()}
function home(){app.innerHTML=`<section class="page home-page"><div class="home-carousel" id="home-carousel"><img class="home-slide" src="assets/home.png" alt="夜晚在家吃火锅"><img class="home-slide" src="assets/home3.png" alt="温暖的双人晚餐"></div><div class="home-shade"></div><img class="home-logo" src="assets/icon5.png" alt="朝夕食事"><div class="carousel-dots"><button class="active" data-slide="0" aria-label="第一张图片"></button><button data-slide="1" aria-label="第二张图片"></button></div></section>`;const carousel=document.querySelector('#home-carousel'),dots=[...document.querySelectorAll('[data-slide]')];let current=0;const show=i=>{current=i;carousel.scrollTo({left:carousel.clientWidth*i,behavior:'smooth'});dots.forEach((d,n)=>d.classList.toggle('active',n===i))};dots.forEach(d=>d.onclick=()=>show(Number(d.dataset.slide)));carousel.addEventListener('scroll',()=>{const i=Math.round(carousel.scrollLeft/carousel.clientWidth);if(i!==current){current=i;dots.forEach((d,n)=>d.classList.toggle('active',n===i))}},{passive:true});homeTimer=setInterval(()=>show(current?0:1),5000)}
function order(query=''){const list=dishes.filter(d=>d.name.includes(query));app.innerHTML=`<section class="page"><div class="hero"><img src="assets/2.jpg" alt="聚餐"><div class="search-row"><input id="dish-search" class="search" value="${escapeHtml(query)}" placeholder="查找菜品"><button class="gear" id="settings" aria-label="菜品设置"><img src="assets/设置.png" alt=""></button></div></div><h2 class="section-title">菜品一览</h2><div class="dish-grid">${list.map(d=>`<article class="dish-card"><img src="${d.image}" alt="${escapeHtml(d.name)}"><div class="dish-info"><span>${escapeHtml(d.name)}</span><button class="add ${cart.includes(d.id)?'selected':''}" data-add="${d.id}" aria-label="选择${escapeHtml(d.name)}">${cart.includes(d.id)?'✓':'+'}</button></div></article>`).join('')}</div>${cart.length?`<div class="cart-bar"><img src="assets/icon8.png" alt=""><strong>× ${cart.length}</strong><button id="confirm">确认</button></div>`:''}</section>`;document.querySelector('#dish-search').addEventListener('input',e=>order(e.target.value));document.querySelector('#settings').onclick=openSettings;document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>toggleDish(b));document.querySelector('#confirm')?.addEventListener('click',confirmMenu)}
function toggleDish(btn){const id=btn.dataset.add,i=cart.indexOf(id);if(i<0){cart.push(id);btn.classList.add('shake');setTimeout(()=>btn.classList.remove('shake'),240)}else cart.splice(i,1);save();setTimeout(()=>order(document.querySelector('#dish-search')?.value||''),i<0?150:0)}
function confirmMenu(){menu=[...cart];cart=[];checked=[];save();toast('采购清单已生成');setTimeout(()=>go('shop'),350)}
function mergeQuantities(values){const parsed=values.map(v=>String(v).trim().match(/^(\d+(?:\.\d+)?)\s*(.*)$/));if(parsed.every(Boolean)){const units=[...new Set(parsed.map(x=>x[2]))];if(units.length===1){const total=parsed.reduce((sum,x)=>sum+Number(x[1]),0);return `${Number(total.toFixed(2))}${units[0]}`}}return [...new Set(values.map(v=>String(v).trim()))].join(' + ')}
function ingredients(){const m=new Map;menu.forEach(id=>dishes.find(d=>d.id===id)?.ingredients.forEach(([n,q])=>{const name=String(n).trim();if(!name)return;if(!m.has(name))m.set(name,[]);m.get(name).push(q)}));return [...m].map(([name,qty])=>({name,qty:mergeQuantities(qty)}))}
function shop(){const chosen=menu.map(id=>dishes.find(d=>d.id===id)).filter(Boolean),items=ingredients();app.innerHTML=`<section class="page"><img class="brand" src="assets/shopping-title.png" alt="采购清单"><h3>今日菜单</h3><div class="menu-chips">${chosen.length?chosen.map((d,i)=>`<span class="chip">${i+1}　${escapeHtml(d.name)}</span>`).join(''):'<span>还没有确认菜单</span>'}</div><strong class="small-label">需购买食材</strong><div class="shopping-list">${items.map(x=>`<button class="shop-item ${checked.includes(x.name)?'done':''}" data-item="${escapeHtml(x.name)}">${escapeHtml(x.name)}　${escapeHtml(x.qty)}</button>`).join('')||'<div class="empty">请先去点单页选择今天想吃的菜</div>'}</div>${items.length?`<div class="list-actions"><button class="soft-btn" id="all-done">全部完成</button><button class="soft-btn" id="clear-done">清除完成项</button></div>`:''}</section>`;document.querySelectorAll('[data-item]').forEach(b=>b.onclick=()=>{const n=b.dataset.item,i=checked.indexOf(n);if(i<0){checked.push(n);b.classList.add('shake')}else checked.splice(i,1);save();setTimeout(shop,180)});document.querySelector('#all-done')?.addEventListener('click',()=>{checked=items.map(x=>x.name);save();shop()});document.querySelector('#clear-done')?.addEventListener('click',()=>{checked=[];save();shop()})}
function recipe(selected=dishes[0]?.id,query=''){const d=dishes.find(x=>x.id===selected)||dishes[0];app.innerHTML=`<section class="page"><div class="recipe-hero"><img src="${d?.image||'assets/icon7.png'}" alt="${escapeHtml(d?.name||'食谱')}"></div><div class="recipe-search"><input id="recipe-search" class="search" value="${escapeHtml(query)}" placeholder="查找菜品"></div><h2 class="section-title">烹饪步骤</h2>${d?`<div class="steps">${d.steps.map((s,i)=>`<div class="step"><span>${i+1}</span><p>${escapeHtml(s)}</p></div>`).join('')}</div>`:'<div class="empty">还没有菜品</div>'}</section>`;document.querySelector('#recipe-search').addEventListener('input',e=>{const q=e.target.value,m=dishes.find(x=>x.name.includes(q));recipe(m?.id||selected,q)})}
function openSettings(){modalRoot.innerHTML=`<div class="modal-wrap"><section class="modal"><div class="modal-head"><h2>菜品管理</h2><button class="close" id="close">×</button></div><div class="manage-list">${dishes.map(d=>`<div class="manage-item"><img src="${d.image}" alt=""><strong>${escapeHtml(d.name)}</strong><div class="manage-actions"><button class="edit-button" data-edit="${d.id}">编辑</button><button class="danger" data-delete="${d.id}">删除</button></div></div>`).join('')}</div><h3>添加新菜品</h3><form class="form" id="dish-form"><input name="name" required placeholder="菜品名称"><label class="upload-field">＋ 添加菜品图片<input name="imageFile" type="file" accept="image/*" required></label><img class="upload-preview" id="upload-preview" alt="图片预览"><textarea name="ingredients" required rows="3" placeholder="食材，每行格式：鸡蛋|3个"></textarea><textarea name="steps" required rows="4" placeholder="步骤，每行一步"></textarea><button class="primary">保存菜品</button></form></section></div>`;document.querySelector('#close').onclick=closeModal;document.querySelector('.modal-wrap').onclick=e=>{if(e.target.classList.contains('modal-wrap'))closeModal()};document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openEditDish(b.dataset.edit));document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{if(confirm('确定删除这道菜吗？')){const id=b.dataset.delete;dishes=dishes.filter(d=>d.id!==id);cart=cart.filter(x=>x!==id);menu=menu.filter(x=>x!==id);save();openSettings();order()}});const form=document.querySelector('#dish-form'),fileInput=form.elements.imageFile,preview=document.querySelector('#upload-preview');fileInput.onchange=()=>{const file=fileInput.files[0];if(file){preview.src=URL.createObjectURL(file);preview.classList.add('visible')}};form.onsubmit=async e=>{e.preventDefault();const file=fileInput.files[0];if(!file){toast('请先添加菜品图片');return}const button=form.querySelector('.primary');button.disabled=true;button.textContent='正在处理图片…';try{const f=new FormData(form),id='dish-'+Date.now(),image=await imageFileToDataUrl(file);dishes.push({id,name:f.get('name').trim(),image,ingredients:f.get('ingredients').split('\n').map(x=>x.split('|').map(y=>y.trim())).filter(x=>x[0]),steps:f.get('steps').split('\n').map(x=>x.trim()).filter(Boolean)});save();closeModal();order();toast('菜品已添加')}catch{button.disabled=false;button.textContent='保存菜品';toast('图片处理失败，请换一张图片')}}}
function openEditDish(id){const d=dishes.find(x=>x.id===id);if(!d)return;modalRoot.innerHTML=`<div class="modal-wrap"><section class="modal"><div class="modal-head"><h2>编辑菜品</h2><button class="close" id="close">×</button></div><form class="form" id="edit-form"><input name="name" required value="${escapeHtml(d.name)}" placeholder="菜品名称"><label class="upload-field">＋ 替换菜品图片（可选）<input name="imageFile" type="file" accept="image/*"></label><img class="upload-preview visible" id="edit-preview" src="${d.image}" alt="当前菜品图片"><textarea name="ingredients" required rows="4" placeholder="食材，每行格式：鸡蛋|3个">${escapeHtml(d.ingredients.map(x=>x.join('|')).join('\n'))}</textarea><textarea name="steps" required rows="6" placeholder="步骤，每行一步">${escapeHtml(d.steps.join('\n'))}</textarea><button class="primary">保存修改</button><button class="soft-btn" type="button" id="back-settings">返回菜品管理</button></form></section></div>`;document.querySelector('#close').onclick=closeModal;document.querySelector('#back-settings').onclick=openSettings;const form=document.querySelector('#edit-form'),fileInput=form.elements.imageFile,preview=document.querySelector('#edit-preview');fileInput.onchange=()=>{const file=fileInput.files[0];if(file)preview.src=URL.createObjectURL(file)};form.onsubmit=async e=>{e.preventDefault();const button=form.querySelector('.primary');button.disabled=true;button.textContent='正在保存…';try{const f=new FormData(form),file=fileInput.files[0];d.name=f.get('name').trim();d.ingredients=f.get('ingredients').split('\n').map(x=>x.split('|').map(y=>y.trim())).filter(x=>x[0]);d.steps=f.get('steps').split('\n').map(x=>x.trim()).filter(Boolean);if(file)d.image=await imageFileToDataUrl(file);save();closeModal();render();toast('菜品已更新')}catch{button.disabled=false;button.textContent='保存修改';toast('保存失败，请稍后再试')}}}
function closeModal(){modalRoot.innerHTML=''}function go(p){page=p;location.hash=p;render();scrollTo(0,0)}
document.querySelectorAll('.bottom-nav button').forEach(b=>b.onclick=()=>go(b.dataset.page));window.addEventListener('hashchange',()=>{page=location.hash.slice(1)||'home';render()});
const accountObserver=new MutationObserver(()=>{const modal=document.querySelector('.modal');if(!modal||!CookCloud.session||document.querySelector('#cloud-logout'))return;const button=document.createElement('button');button.id='cloud-logout';button.className='soft-btn logout-button';button.textContent='退出当前账号';button.onclick=()=>{CookCloud.logout();closeModal();showLogin()};modal.append(button)});accountObserver.observe(modalRoot,{childList:true,subtree:true});
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));render();if(CookCloud.session)connectCloud();else showLogin();
